### ISSUE TITLE
[BUG] API for Sonarr and Radarr has changed.

### ISSUE THREAD

**Issue by modem7** [Boerderij/Varken#233]
**Describe the bug**
API for Sonarr and Radarr has changed to v3.

**To Reproduce**
```
today at 15:25:082022-03-29 15:25:08 : DEBUG : connectionpool : http://192.168.0.254:7878 "GET /api/movie HTTP/1.1" 404 0
today at 15:25:082022-03-29 15:25:08 : DEBUG : connectionpool : http://192.168.0.254:7878 "GET /api/queue HTTP/1.1" 404 0
today at 15:25:082022-03-29 15:25:08 : INFO : helpers : This url doesnt even resolve: http://192.168.0.254:7878/api/movie
today at 15:25:082022-03-29 15:25:08 : INFO : helpers : This url doesnt even resolve: http://192.168.0.254:7878/api/queue
```

**Additional context**
/api/v3/
https://github.com/Sonarr/Sonarr/wiki/API
https://radarr.video/docs/api/

Edit: can see the develop branch seems to have resolved. Please close if deemed "resolved by develop branch".

**Comment by samwiseg0** [comment]
This has already been fixed in develop.

**Comment by magoogle** [comment]
This is still an issue running container develop 4.3.0.6671-ls74 by [linuxserver.io]

Is there another version?

**Comment by Watever44** [comment]
I have the same issue. What should I do ?
I suppose it was fixed in stable version too ? or not ?

**Comment by modem7** [comment]
> I have the same issue. What should I do ?
> I suppose it was fixed in stable version too ? or not ?

Stable hasn't been updated for a number of years. I've been using the develop branch (boerderij/varken:develop) with no issues as that had a release last month.
